### ISSUE TITLE
Google virtual keyboard element image broken for Arabic

### ISSUE THREAD

**Issue by Stephanie1125** [google/personfinder#293]
![bug](https://cloud.githubusercontent.com/assets/15961861/18822321/7e5f4168-83e9-11e6-9f0f-a479200ebc9c.png)

**Comment by gimite** [comment]
Can you put the image directly instead of using screenshot.googleplex.com? Because screenshot.googleplex.com is only visible to Googlers, but non-Googlers also look at issues.

I often use screenshot.googleplex.com during code reviews with Googlers because it's convenient and usually only the reviewer and the author reads code reviews. But we should not use it for issue description.

**Comment by Stephanie1125** [comment]
i see! Uploaded image.

**Comment by nworden** [comment]
Are we sure this is a Person Finder issue rather than a bug with the keyboard itself? Does this image come from Person Finder code, or is it otherwise affect by PF code?

**Comment by gimite** [comment]
I don't know. It looks likely an issue of the keyboard itself. It might be good to confirm that it is not caused by our usage of the keyboard, but I'm personally also OK to simply close the bug.

**Comment by nworden** [comment]
I think I've confirmed the issue is with the keyboard itself: it is pointing to a reasonable-looking URL (http://www.google.com/webelements/images/gwe_transparent_130x20.png), there just isn't a file there anymore. Since the Virtual Keyboard was deprecated in 2014, it's not surprising that files may have moved or been deleted without anyone updating the keyboard code.
