### ISSUE TITLE
Migrate from appcfg.py to gcloud command

### ISSUE THREAD

**Issue by gimite** [google/personfinder#395]
Looks `gcloud` command is the standard way to configure App Engine app nowadays (though `appcfg.py` is still available). It would be better to migrate our tools / instructions to use `gcloud` command.

**Comment by myoshimu** [comment]
Fix might be required for following directory:
tools/gae
tools/console

**Comment by myoshimu** [comment]
https://cloud.google.com/appengine/docs/standard/java/tools/migrating-from-appcfg-to-gcloud

**Comment by gimite** [comment]
Even with this one resolved, should we migrate to Python 3, since its support in App Engine is still beta?:
https://cloud.google.com/appengine/docs/standard/python3/quickstart

> This is a beta release of Python 3.7 in the App Engine standard environment. This feature might be changed in backward-incompatible ways and is not subject to any SLA or deprecation policy.

Stability is important for our product, so I'm a bit concerned to use an infra without SLA. It is up to you though.

**Comment by nworden** [comment]
This is just one of many, many things we have to do before we eventually make the switch to Python 3. We won't be using the v3 runtime anytime soon.

**Comment by gimite** [comment]
I personally feel it may be too early for us to take time to start preparing for Python 3 migration at this moment when it is unclear when App Engine Python 3 support exits beta. But it is also up to you.

**Comment by nworden** [comment]
I'm not sure if you've seen the doc I sent to the team list yesterday (I'm on my phone right now and don't have my work account on it), but it looks like the Python 3 migration is going to be a lot of work for us because a lot of AE APIs (e.g., the Users service) aren't being supported for 3:
https://cloud.google.com/appengine/docs/standard/python3/python-differences#app_engine_apis
It's hard to make good plans because we don't know when the v3 runtime is coming out of beta or how long they're going to support 2.7, but I think it'd be good to start doing some of the work to prepare now, to be safe.

**Comment by gimite** [comment]
Oh sorry I have just read the doc :) I agree that we should eventually migrate to Python 3, so it sounds good to start from something stable, like migrating to Python 3 language itself.

**Comment by myoshimu** [comment]
@gimite @nworden 
Sorry for the delay in seeing this and let me consult how we should handle this issue.

When I tried to use Google Cloud SDK instead of the original App Engine SDK, it worked with the following command as the old SDK(including new React UI) without problem.
$ /opt/google-cloud-sdk/bin/dev_appserver.py app/app.yaml --port 8000 --admin_port=8001

I saw [the generation comparison](https://cloud.google.com/appengine/docs/standard/runtimes) but as far as I see python2.7 is compatible with gVisor(2nd Gen GAE).

So whet I should do seems to simply replacing line 42 of tools/gae to gcloud command. Is my understanding correct?
If so, I think we can also leave current tools/gae and append the description how to use Google Cloud SDK in the (Getting Started guide)[https://github.com/google/personfinder/wiki/GettingStarted].
Does it sound OK?

Please let me know your thoughts.

Thanks!
Miki

**Comment by gimite** [comment]
Thanks for taking a look at this!

tools/gae can also be used in this way:
```
$ tools/gae update app -A my-app-id --noauth_local_webserver
```
as documented in:
https://github.com/google/personfinder/wiki/GettingStarted

Have you confirmed if the command works as is with Cloud SDK?

> So what I should do seems to simply replacing line 42 of tools/gae to gcloud command.

What about line 39? Don't you need to update the line too because dev_appserver.py is now at /opt/google-cloud-sdk/bin/dev_appserver.py?

> If so, I think we can also leave current tools/gae without any modification and append the description how to use Google Cloud SDK in the Getting Started guide.

If we leave tools/gae as is, it won't work with Cloud SDK, right? I would prefer to update it to make it work with Cloud SDK to avoid confusion.

**Comment by ryosuketc** [comment]
App Engine **standalone** SDK seems to have gotten unavailable in Aug. 2020., which forces us to migrate out of `appcfg`.
https://cloud.google.com/appengine/docs/standard/python/sdk-gcloud-migration

**Comment by ryosuketc** [comment]
I have found `APPENGINE_DIR` strings in the following files (but not yet examined the usage).

-   config files
https://github.com/google/personfinder/blob/master/.travis.yml
https://github.com/google/personfinder/blob/master/Dockerfile

-   tests
https://github.com/google/personfinder/blob/master/tests/server_tests.py

-   tools
https://github.com/google/personfinder/blob/master/tools/gae
https://github.com/google/personfinder/blob/master/tools/common.sh

-   pfif-tools
https://github.com/google/personfinder/blob/master/tools/pfif-tools/tools/gae
https://github.com/google/personfinder/blob/master/tools/pfif-tools/tools/common.sh
https://github.com/google/personfinder/blob/master/tools/pfif-tools/tools/remote_api.py

I can not find the usage on [tools/console](https://github.com/google/personfinder/blob/master/tools/console), which was mentioned [above](https://github.com/google/personfinder/issues/395#issuecomment-403359757).

**Comment by ryosuketc** [comment]
Searching for `tools/gae` in our wiki ([search result](https://github.com/google/personfinder/search?q=repo%3Agoogle%2Fpersonfinder+tools%2Fgae&type=wikis)), I only found two types of usages, which could mean that we only expect these arguments (run or update).
`tools/gae run ...`
`tools/gae update ...`

**Comment by gimite** [comment]
`tools/console` may not be mentioned anywhere, but it is still a useful tool (which allows us to interactively run Python code against a PF instance on AppEngine), so it would be great if we can keep it working.

> Searching for tools/gae in our wiki (search result), I only found two types of usages, which could mean that we only expect these arguments (run or update).

This is probably true.

Note that we don't necessarily need to keep command line syntax of these commands. We just need an alternative way to do the same things (and update documents).

Among what you find, these would be in high priority:

* tests
* tools/gae, tools/common

Others can be done later. e.g., I believe none of the core developers are actively using the Docker setup or pfif-tools now.

**Comment by ryosuketc** [comment]
Thanks for the advice. I will prioritize the two scripts. In the meantime, https://github.com/google/personfinder/issues/771 has to be addressed first.

**Comment by ryosuketc** [comment]
> `tools/console` may not be mentioned anywhere, but it is still a useful tool (which allows us to interactively run Python code against a PF instance on AppEngine), so it would be great if we can keep it working.
> 

TODO: This has to be looked into and addressed.

> > Searching for tools/gae in our wiki (search result), I only found two types of usages, which could mean that we only expect these arguments (run or update).
> 
> This is probably true.
> 
> Note that we don't necessarily need to keep command line syntax of these commands. We just need an alternative way to do the same things (and update documents).
> 
> Among what you find, these would be in high priority:
> 
> * tests
> * tools/gae, tools/common
> 

`tools/gae` was deleted and `tools/common` was updated in https://github.com/google/personfinder/pull/773.
tests do not fail after the change. Hence it is likely that no updates are needed there.

> Others can be done later. e.g., I believe none of the core developers are actively using the Docker setup or pfif-tools now.

**Comment by ryosuketc** [comment]
@gimite re: `tools/console`:

I found some documents referring to it - [search results](https://github.com/google/personfinder/search?q=tools%2Fconsole&type=wikis).

-   On **localhost** the command mostly works fine without any modification since it depends on app engine python libraries, not `appcfg` command (which is deprecated).
    -   **Might the document, however, be outdated regarding the default behavior?**
        -   [DeveloperGuideGHC11](https://github.com/google/personfinder/wiki/DeveloperGuideGHC11) says:
        -   > tools/console # Connects to localhost port 8000 by default
        - However, when I run `tools/console` while running a host on the port (`dev_appserver.py app --port=8000 --admin_port=8080`), it is not connected.
        -   It works fine when I specify it in the arguments.
        - I am unsure if the default behavior still holds true as long as I look into the source codes in `tools/console` and `tools/console.py`.  

```
 % tools/console
Not connected.  Use connect(appserver_url) to connect.
from model import *
from setup_pf import *
>>>
```
```
 % tools/console localhost:8000
Connected to: localhost:8000
from model import *
from setup_pf import *
dev~None>
```

-   On **production server**, authentication fails. I guess it is due to my permission, not due to the script itself. Could you help verify it?
```
% tools/console googlepersonfinder.appspot.com
Go to the following link in your browser:
https://accounts.google.com/o/oauth2/v2/auth?...(omitted)...
Enter verification code:
```
```
Authorization Error
Error 401: invalid_client
The OAuth client was not found.
```

**Comment by gimite** [comment]
> Might the document, however, be outdated regarding the default behavior?

Yeah it looks the behavior in the document is outdated. I believe it's expected that it does nothing when no arguments are provided.

> On production server, authentication fails. I guess it is due to my permission, not due to the script itself. Could you help verify it?

Replied this in an email since this may be something to do with our internal setup.

**Comment by ryosuketc** [comment]
> Yeah it looks the behavior in the document is outdated. I believe it's expected that it does nothing when no arguments are provided.

The document is updated.
https://github.com/google/personfinder/wiki/DeveloperGuideGHC11/_compare/d80204d85ee3117217b284ace1bf3c3be091dd6b...440e5565751a88ea79580b6fb16bef8427e3ccab

> Replied this in an email since this may be something to do with our internal setup.

Thanks. No edition seems to be needed for `tools/console`.
Since the major use cases have been addressed as commented above (https://github.com/google/personfinder/issues/395#issuecomment-774920041), I am closing the issue for now.

Someone could reopen the issue or file a new one if any other usage of `appcfg.py` is found in the future.

**Comment by gimite** [comment]
Great, thanks!

> Thanks. No edition seems to be needed for tools/console.

Ideally it should be mentioned somewhere that you need to set up the application default credential for it (it isn't obvious that the tool depends on it), though I'm not sure where the best place for it is. Maybe at least in the comment of tools/console?

**Comment by ryosuketc** [comment]
I have added it to `tools/console`and DeveplerFaq.
https://github.com/google/personfinder/wiki/DeveloperFaq/_compare/568a38cf4d787c4663b3389e8dd2d9c60714b1b5...e8e3ed3e8e00c80ad7562f6858e119bc04acd83c
