### ISSUE TITLE
Sitemap and sitemap ping not working

### ISSUE THREAD

**Issue by gimite** [google/personfinder#456]
I found that sitemap and sitemap ping of Person Finder are not working.

And it looks like it is failing for long, at least for 7 years.

Maybe we can just remove it because Google probably does a good job finding pages quickly without sitemap, and we actually have seen no issues in these 7 years? WDYT? @nworden 

One potential counterargument is that it may still help Google to find a new repository even more quickly.

I noticed that because "sitemap ping" cron job is failing in our production. Also https://google.org/personfinder/japan/sitemap returns an error.

I found multiple problems:
* The URL specified in the cron job, /sitemap/ping?search_engine=google, is 404. It misses a repository name.
* /sitemap fails due to out of memory.
* The datastore contained two entities of StaticSiteMapInfo, both created at 2011, while the code expects only one entity. I have just deleted one of them.

**Comment by nworden** [comment]
It looks like the sitemap is designed to include links to person pages, which doesn't seem like desirable behavior today (and we're setting noindex on person pages anyway).

I think I could simplify it a lot by just making it a map to repo pages and shared pages (like the terms of service page). Maybe also change it to only ping when a new repo is launched (instead of on a cron every 15 minutes). What do you think? Any reason not to?

**Comment by gimite** [comment]
SGTM.

**Comment by will44047** [comment]
Go for it
