### ISSUE TITLE
Figure out if api.py needs to use a dict for full-text search

### ISSUE THREAD

**Issue by nworden** [google/personfinder#488]
Random thing I came across while doing some refactoring today. When external search backends doesn't produce any results and full-text search is enabled, api.py makes a call to full_text_search.search with query_string as the query_dict argument:
https://github.com/google/personfinder/blob/master/app/api.py#L541

full_text_search.search does appear to expect that query_dict actually be a dict: the first thing it does is call .get('name', ''):
https://github.com/google/personfinder/blob/master/app/full_text_search.py#L190

api.py's query_string does appear to really just be a string though: it pulls it from the request GET parameters. I'm not really sure how this is working, or if it even is (maybe that codepath is never followed in prod or in tests).

**Comment by gimite** [comment]
Looks like a bug. Full text search hasn't been launched, and probably we have never tested API call with full text search enabled. We were not able to work on launching full text search for years (though I still believe we eventually should), so it may be OK just to leave it.

But if we want to fix it, we should probably just pass `{name: query_string}` instead because the API doesn't support passing location query (yet).
